CREATE DATABASE FASHION;
USE FASHION;
 

 -------------TABLE 1------------

 DROP TABLE CATEGORY;

 CREATE TABLE CATEGORY 
 (
 CATEGORY_ID	INT PRIMARY KEY IDENTITY(100,1),
 CATEGORY_NAME VARCHAR(20),
 TAX_PERCNT			INT
 );

 INSERT INTO CATEGORY (CATEGORY_NAME,TAX_PERCNT)
 VALUES('FORMAL' ,28),('CASUAL', 28),('SEMI_CASUAL',28);

 SELECT* FROM CATEGORY;



 
 -----TABLE 2---------

 DROP TABLE ITEM_DETAILS

 CREATE TABLE ITEM_DETAILS
 (
  ITEM_ID INT PRIMARY KEY IDENTITY (10,1),
  CATEGORY_ID INT,
  ITEM_NAME VARCHAR(10),
  SIZE_ID INT,
  STYLE VARCHAR(20),
  SHARE INT,
  GENDER VARCHAR(20) CHECK(GENDER IN('M','F')),

  PRICE MONEY

  CONSTRAINT FK_CTGRY_ID FOREIGN KEY(CATEGORY_ID) REFERENCES CATEGORY(CATEGORY_ID),
  CONSTRAINT FK_SIZE_ID FOREIGN KEY(SIZE_ID) REFERENCES SIZE_DETAILS(SIZE_ID)

 );


 INSERT INTO ITEM_DETAILS (CATEGORY_ID, ITEM_NAME,SIZE_ID, STYLE, GENDER,  PRICE,SHARE)
 VALUES(100,'SHIRT',1,'CHECKERED','M',1000,80),
		(101,'PANT',2,'SKIN FIT','M',2000,70),
		(100,'TROUSER',1,'FIT','M',3000,60),
		(101,'T-SHIRT',3,'ROUND-NECK','M',6000,55),
		(102,'PYJAAMA',2,'FULL-SLEEVE','M',4000,66),
		(100,'TRACKSUIT',4,'RUNNING-STYLE','M',5000,66),
		(101,'BLUEBERRY',5,'NORMAL-STYLE','F',7000,76);

 
 
 
 ---------TABLE 3---------------
 DROP TABLE SIZE_DETAILS

 CREATE TABLE SIZE_DETAILS
 (
  SIZE_ID INT IDENTITY(1,1) PRIMARY KEY,
  SIZE  VARCHAR(20) CHECK(SIZE IN('S','SX','M','L','XL','XXL')),
 );

 INSERT INTO SIZE_DETAILS (SIZE)
 VALUES('S'),('SX'),('M'),('L'),('XL'),('XXL');


 SELECT * FROM ITEM_DETAILS
 SELECT * FROM SIZE_DETAILS
 SELECT * FROM CATEGORY

 
 ---1ST QUESTION
 

 SELECT CATEGORY_NAME AS CATEGORY_NAME ,AVG(PRICE) AS AVG_COST
FROM CATEGORY C
JOIN ITEM_DETAILS I ON (C.CATEGORY_ID=I.CATEGORY_ID) GROUP BY CATEGORY_NAME;

 ----2ND QUESTION

 --SELECT I.ITEM_ID, C.CATEGORY_NAME, I.ITEM_NAME FROM ITEM_DETAILS I JOIN CATEGORY C ON 
 --(I.CATEGORY_ID=C.CATEGORY_ID) WHERE I.CATEGORY_ID IN (SELECT CATEGORY_ID FROM ITEM_DETAILS
 --WHERE ITEM_NAME = 'BLUEBERRY')

 SELECT  C.CATEGORY_ID,CATEGORY_NAME, ITEM_NAME FROM ITEM_DETAILS I FULL JOIN CATEGORY C ON I.CATEGORY_ID =C.CATEGORY_ID
 WHERE ITEM_NAME = 'BLUEBERRY'
 


 SELECT CATEGORY_ID FROM ITEM_DETAILS WHERE ITEM_NAME = 'BLUEBERRY'

 



 ----3RD QUESTION

 SELECT I.ITEM_NAME, S.SIZE FROM ITEM_DETAILS I LEFT JOIN SIZE_DETAILS S ON 
 (I.SIZE_ID = S.SIZE_ID) WHERE S.SIZE_ID = 1 OR S.SIZE_ID = 2 ORDER BY ITEM_NAME